version: '3'

services:
  gitexercises:
    restart: unless-stopped
    environment:
      DB_HOST: gitexercises-db
      DB_NAME: gitexercises
      DB_USER: ${DB_USER:-gitexercises}
      DB_PASSWORD: ${DB_PASSWORD:-gitexercises}
      DOMAIN_NAME: ${DOMAIN_NAME:-gitexercises.com}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        GIT_REPO: ${GIT_REPO:-}
        DOMAIN_NAME: ${DOMAIN_NAME:-gitexercises.com}
        SITE_ADMIN_NAME: ${SITE_ADMIN_NAME:-Gitexercises Admin}
        SITE_ADMIN_EMAIL: ${SITE_ADMIN_EMAIL:-admin@gitexercises.com}
    depends_on:
     - gitexercises-db
    ports:
     - ${PORT_HTTP}:80
    logging:
      options:
        max-size: 50m

  gitexercises-db:
    restart: unless-stopped
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: ${DB_USER:-gitexercises}
      MYSQL_PASSWORD: ${DB_PASSWORD:-gitexercises}
      MYSQL_DATABASE: gitexercises
    volumes:
       - /var/lib/mysql
       - ../backend/schema/gitexercises.sql:/docker-entrypoint-initdb.d/gitexercises.sql
    logging:
      options:
        max-size: 50m

networks:
  default: ~
