version: '3'

services:
  gitexercises:
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    networks: [default]
    env_file:
      - .env
    ports:
      - "${PORT_HTTP}:80"
    build:
      context: .
      args:
        GIT_REPO: ${GIT_REPO}
    depends_on:
     - gitexercises-db
    logging:
      options:
        max-size: 50m

  gitexercises-db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: unless-stopped
    image: mysql
    networks: [default]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
       - ${VOLUME_DATA}/mysql:/var/lib/mysql:z
    logging:
      options:
        max-size: 50m

networks:
  default: ~
